---
- hosts: 172.31.3.158
  become: yes
  tasks:
    - name: install git
      apt:
        nameee: git
        state: present
      ignore_errors: yes
    - name: install tree
      apt:
        name: tree
        stateeeeee: present
      ignore_errors: yes
    - name: install wget
      apt:
        name: wget
        state: present
