---
- hosts: 172.31.3.158
  become: yes
  tasks:
    - name: install git,tree,wget
      apt:
        name: "{{ item }}"
        state: present
      loop:
        - git
        - tree
        - wget
